#точно нннадо
#1. настройка AMP + redis + memcache бонусом
# Запустим биииитрикс

#2. деплой на прод
# Heroku?

#3. бекапы/снапшоты
# Решения для бекапирования


#4. создаем свой контейнер
#5. мониторинг и GUI
#6. возможно можно затронуть тему scale


version: '3.6'

services:
    nginx:
        build: nginx
        volumes:
            # Time Zone and Local Time
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ${PROJECT_PASS}:/var/www
        ports:
            - 80:80
        depends_on:
            - php-fpm
        networks:
            - project


    php-fpm:
        build: php-fpm
        volumes:
            # Time Zone and Local Time
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ${PROJECT_PASS}:/var/www
        networks:
          - project

networks:
    project:
        driver: bridge