#точно нннадо
#1. настройка AMP + redis + memcache бонусом
# Запустим биииитрикс

#2. деплой на прод
# Heroku?

#3. бекапы/снапшоты
# Решения для бекапирования


#4. создаем свой контейнер
#5. мониторинг и GUI
#6. возможно можно затронуть тему scale


version: '3.6'

services:
