#точно нннадо
#1. настройка AMP + redis + memcache бонусом
# Запустим биииитрикс

#2. деплой на прод
# Heroku?

#3. бекапы/снапшоты
# Решения для бекапирования


#4. создаем свой контейнер
#5. мониторинг и GUI
#6. возможно можно затронуть тему scale


version: '3.6'

services:
    nginx:
        build: nginx
        volumes:
            # Time Zone and Local Time
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ${PROJECT_PASS}:/var/www
        ports:
            - 80:80
        depends_on:
            - php-fpm
        networks:
            project:
                aliases:
                    - bitrix.local

    php-fpm:
        build: php-fpm
        volumes:
            # Time Zone and Local Time
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ${PROJECT_PASS}:/var/www
        networks:
          - project
          - mysql

    mysql:
        build: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            # Time Zone and Local Time
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - mysql_data:/var/lib/mysql
        networks:
            - mysql


networks:
    project:
        driver: bridge
    mysql:
        driver: bridge

volumes:
    mysql_data:
        external: false
